### ISSUE TITLE
Shotgun Sentry Bug

### ISSUE THREAD

**Issue by BOBAMAx** [cmss13-devs/cmss13#7045]
### Testmerges

doesnt matter

### Description of the bug

https://github.com/user-attachments/assets/594a2410-cc4d-4c6a-8b40-d9854d838e13

shotgun sentry bonus projectiles originate from the mob that placed it down instead of the shotgun sentry.

now tested on live thanks to the smellyhippie himself

This is actually pretty abusable if you know how it works because you can bait xenos into eating 130 damage of bonus projectile while not actually being in range of the sentry gun while resting/otherwise incapacitated.

### What's the difference with what should have happened?

bonus projectiles should not be coming from the mob that placed the sentry but the sentry itself

### How do we reproduce this bug?

put down a shotgun sentry and watch it do this

### Issue Bingo

- [X] Issue could be reproduced at least once
- [x] Issue happened in a recent (less than 7 days ago) round
- [x] Couldn't find an existing issue about this (https://github.com/cmss13-devs/cmss13/issues)

**Comment by Doubleumc** [comment]
Likely related to https://github.com/cmss13-devs/cmss13/pull/6784

**Comment by vero5123** [comment]
throwing shade in bug reports is always peak cm.

**Comment by Ansekishokuu** [comment]
Probably fixed with #7406, tested and it didn't happen to me.

**Comment by BOBAMAx** [comment]
@Drulikar @Ansekishokuu this is still an issue, just tested it on live

**Comment by BOBAMAx** [comment]
https://www.youtube.com/watch?v=MhJTFaawDWg
